baseURL = 'http://ghbrown.github.io/'
languageCode = 'en-us'
title = 'Gabriel H. Brown'
theme = "color_splotch"

[markup.goldmark.renderer]
  unsafe = true # allow HTML in md files

[menu]
  [[menu.main]]
    name = "ABOUT ME"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "RESEARCH"
    url = "/topics/research"
    weight = 2
  [[menu.main]]
    name = "PUBLICATIONS"
    url = "/topics/publications"
    weight = 3
  [[menu.main]]
    name = "HOBBIES & INTERESTS"
    url = "/topics/hobbies_and_interests"
    weight = 4
  [[menu.main]]
    name = "RANDOM"
    url = "/topics/random/random"
    weight = 5


