baseURL = 'https://ghbrown.net/'
languageCode = 'en-us'
author = 'Gabriel H. Brown'
title = 'Gabriel H. Brown'
copyright = 'Copyright [Gabriel H. Brown](ghbrown.net).'
desciption = 'Website of Gabriel H. Brown, Graduate Student at University of Texas at Austin.'
theme = 'risotto'

[params.theme]
  palette = 'color-splotch'
  # palette = 'base16-dark'
  # palette = 'windows-95'
  # palette = 'dracula'

[markup.goldmark.renderer]
  unsafe = true # allow HTML in md files

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/topics/research"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/topics/publications"
    weight = 3
  [[menu.main]]
    name = "Open Source"
    url = "/topics/open_source"
    weight = 4
  [[menu.main]]
    name = "Hobbies"
    url = "/topics/hobbies_and_interests"
    weight = 5
  [[menu.main]]
    name = "Post Topics"
    url = "/tags"
    weight = 6


