baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Gabriel H. Brown'
theme = "testTheme"

[markup.goldmark.renderer]
  unsafe = true # allow HTML in md files

[menu]
  [[menu.main]]
    name = "ABOUT ME"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "RESEARCH"
    url = "/topics/research"
    weight = 2
  [[menu.main]]
    name = "PUBLICATIONS"
    url = "/topics/publications"
    weight = 3
  [[menu.main]]
    name = "HOBBIES & INTERESTS"
    url = "/topics/hobbies_and_interests"
    weight = 4
  [[menu.main]]
    name = "RANDOM"
    url = "/topics/random/random"
    weight = 5

# things you'll forget:
# - hugo server doesn't watch for CSS changes, so you have to change
#   a tracked file for it to refresh the website
# - it probably doesn't watch for any changes in themes/ actually

# really just want my site to be 1:1 with old site before moving
# over, then I can figure out improvements one at a time

# current issues:
#- figure out simple scrolling of CSS code blocks (may be tied to width
#  contraints and flex box stuff
#- too long code lines actually widen whole page past 100% window width
#- how to determine syntax highlighting colorscheme
#- rename theme to something sensible
#- see if CSS styling can be simplified to make it a bit more theme
#  agnostic and extensible/flexible
#- set up Hugo CI job thing
#- rearrange and delete files as necessary such that files such that
#  it conforms with Hugo CI Job thing (for example, google certificate
#  should go in static/ not at root of git repo where it currently is

